/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ParameterSelection;

import DataObjects.Pilot;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class OneTimePilotPanel extends javax.swing.JPanel {

    /**
     * Creates new form OneTimePilotPanel
     */
    public OneTimePilotPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capabilityButtonGorup = new javax.swing.ButtonGroup();
        preferenceButtonGroup = new javax.swing.ButtonGroup();
        pilotNameLabel = new javax.swing.JLabel();
        pilotFirstNameInput = new javax.swing.JTextField();
        pilotWeightLabel = new javax.swing.JLabel();
        pilotWeightInput = new javax.swing.JTextField();
        pilotCapabilityLabel = new javax.swing.JLabel();
        pilotPreferenceLabel = new javax.swing.JLabel();
        emergencyContactLabel = new javax.swing.JLabel();
        emergencyContactInput = new javax.swing.JTextField();
        medicalInfoLabel = new javax.swing.JLabel();
        medicalInfoInput = new javax.swing.JTextField();
        studentRadioButton = new javax.swing.JRadioButton();
        proficientRadioButton = new javax.swing.JRadioButton();
        advancedRadioButton = new javax.swing.JRadioButton();
        mildRadioButton = new javax.swing.JRadioButton();
        nominalRadioButton = new javax.swing.JRadioButton();
        aggressiveRadioButton = new javax.swing.JRadioButton();
        pilotLastNameLabel = new javax.swing.JLabel();
        pilotLastNameInput = new javax.swing.JTextField();
        pilotfirstNameLabel = new javax.swing.JLabel();

        pilotNameLabel.setText("Name:");

        pilotFirstNameInput.setBackground(new java.awt.Color(255, 0, 0));
        pilotFirstNameInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pilotFirstNameInputKeyReleased(evt);
            }
        });

        pilotWeightLabel.setText("Weight:");

        pilotWeightInput.setBackground(new java.awt.Color(255, 0, 0));
        pilotWeightInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilotWeightInputActionPerformed(evt);
            }
        });
        pilotWeightInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pilotWeightInputKeyReleased(evt);
            }
        });

        pilotCapabilityLabel.setText("Capability:");

        pilotPreferenceLabel.setText("Preference");

        emergencyContactLabel.setText("Emergency Contact:");

        emergencyContactInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyContactInputActionPerformed(evt);
            }
        });

        medicalInfoLabel.setText("Emergency Medical Info:");

        capabilityButtonGorup.add(studentRadioButton);
        studentRadioButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        studentRadioButton.setSelected(true);
        studentRadioButton.setText("Student");

        capabilityButtonGorup.add(proficientRadioButton);
        proficientRadioButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        proficientRadioButton.setText("Proficient");
        proficientRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proficientRadioButtonActionPerformed(evt);
            }
        });

        capabilityButtonGorup.add(advancedRadioButton);
        advancedRadioButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        advancedRadioButton.setText("Advanced");

        preferenceButtonGroup.add(mildRadioButton);
        mildRadioButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        mildRadioButton.setSelected(true);
        mildRadioButton.setText("Mild");

        preferenceButtonGroup.add(nominalRadioButton);
        nominalRadioButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        nominalRadioButton.setText("Nominal");

        preferenceButtonGroup.add(aggressiveRadioButton);
        aggressiveRadioButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        aggressiveRadioButton.setText("Performance");

        pilotLastNameLabel.setText("Last:");

        pilotLastNameInput.setBackground(new java.awt.Color(255, 0, 0));
        pilotLastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilotLastNameInputActionPerformed(evt);
            }
        });
        pilotLastNameInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pilotLastNameInputKeyReleased(evt);
            }
        });

        pilotfirstNameLabel.setText("First:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emergencyContactInput)
                    .addComponent(medicalInfoInput)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pilotfirstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilotFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pilotLastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pilotLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emergencyContactLabel)
                            .addComponent(medicalInfoLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pilotWeightLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pilotWeightInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pilotNameLabel)
                                    .addComponent(studentRadioButton)
                                    .addComponent(proficientRadioButton)
                                    .addComponent(advancedRadioButton)
                                    .addComponent(pilotCapabilityLabel))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aggressiveRadioButton)
                                    .addComponent(mildRadioButton)
                                    .addComponent(nominalRadioButton)
                                    .addComponent(pilotPreferenceLabel))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pilotNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilotFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilotLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilotLastNameLabel)
                    .addComponent(pilotfirstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilotWeightInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilotWeightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilotCapabilityLabel)
                    .addComponent(pilotPreferenceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proficientRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(advancedRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mildRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nominalRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aggressiveRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emergencyContactLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emergencyContactInput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medicalInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medicalInfoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pilotWeightInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilotWeightInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilotWeightInputActionPerformed

    private void emergencyContactInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyContactInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyContactInputActionPerformed

    private void pilotFirstNameInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pilotFirstNameInputKeyReleased
        // TODO add your handling code here:
        if(pilotFirstNameInput.getText().isEmpty()){
            pilotFirstNameInput.setBackground(Color.RED);
        }
        else
            pilotFirstNameInput.setBackground(Color.GREEN);
    }//GEN-LAST:event_pilotFirstNameInputKeyReleased

    private void pilotWeightInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pilotWeightInputKeyReleased
        // TODO add your handling code here:
        if(pilotFirstNameInput.getText().isEmpty()){
            pilotWeightInput.setBackground(Color.RED);
        }
        else {
            try {
                int weight = Integer.parseInt(pilotWeightInput.getText());
                pilotWeightInput.setBackground(Color.GREEN);
            }catch(NumberFormatException e) {
                pilotWeightInput.setBackground(Color.RED);
            } 
            
        }
    }//GEN-LAST:event_pilotWeightInputKeyReleased

    private void proficientRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proficientRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proficientRadioButtonActionPerformed

    private void pilotLastNameInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pilotLastNameInputKeyReleased
        // TODO add your handling code here:
        if(pilotLastNameInput.getText().isEmpty()){
            pilotLastNameInput.setBackground(Color.RED);
        }
        else
            pilotLastNameInput.setBackground(Color.GREEN);
    }//GEN-LAST:event_pilotLastNameInputKeyReleased

    private void pilotLastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilotLastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilotLastNameInputActionPerformed

    public Pilot getOneTimePilot() {
        if(pilotFirstNameInput.getText().isEmpty())
            JOptionPane.showMessageDialog(pilotFirstNameInput, "Please provide a first name");
        String firstName = pilotFirstNameInput.getText();
        if(pilotLastNameInput.getText().isEmpty())
            JOptionPane.showMessageDialog(pilotLastNameInput, "Please provide a last name");
        String lastName = pilotLastNameInput.getText();
        int weight = 0;
        if(pilotWeightInput.getText().isEmpty())
            JOptionPane.showMessageDialog(pilotWeightInput, "Please provide a weight");
        try{
            weight = Integer.parseInt(pilotWeightInput.getText());
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(pilotWeightInput, "Please provide a VALID weight");
        }
        String capability;
        if(advancedRadioButton.isSelected())
            capability = Capability.ADVANCED;
        else if (proficientRadioButton.isSelected())
            capability = Capability.PROFICIENT;
        else 
            capability = Capability.STUDENT;
        
        String preference;
        if(mildRadioButton.isSelected())
            preference = "Mild";
        else if(nominalRadioButton.isSelected())
            preference = "Nominal";
        else
            preference = "Aggressive";
        
        String emergnecyContact = emergencyContactInput.getText();
        String medInfo = medicalInfoInput.getText();
       
        return (new Pilot(lastName, firstName, weight, capability, preference, emergnecyContact, medInfo));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton advancedRadioButton;
    private javax.swing.JRadioButton aggressiveRadioButton;
    private javax.swing.ButtonGroup capabilityButtonGorup;
    private javax.swing.JTextField emergencyContactInput;
    private javax.swing.JLabel emergencyContactLabel;
    private javax.swing.JTextField medicalInfoInput;
    private javax.swing.JLabel medicalInfoLabel;
    private javax.swing.JRadioButton mildRadioButton;
    private javax.swing.JRadioButton nominalRadioButton;
    private javax.swing.JLabel pilotCapabilityLabel;
    private javax.swing.JTextField pilotFirstNameInput;
    private javax.swing.JTextField pilotLastNameInput;
    private javax.swing.JLabel pilotLastNameLabel;
    private javax.swing.JLabel pilotNameLabel;
    private javax.swing.JLabel pilotPreferenceLabel;
    private javax.swing.JTextField pilotWeightInput;
    private javax.swing.JLabel pilotWeightLabel;
    private javax.swing.JLabel pilotfirstNameLabel;
    private javax.swing.ButtonGroup preferenceButtonGroup;
    private javax.swing.JRadioButton proficientRadioButton;
    private javax.swing.JRadioButton studentRadioButton;
    // End of variables declaration//GEN-END:variables
}
