package ParameterSelection;

import Communications.Observer;
import DataObjects.GliderPosition;

import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dbennett3
 */
public class ParameterSelectionPanel extends javax.swing.JPanel implements Observer {

    private final static String[] tabNames = {"PILOT","GLIDER","AIRFIELD","DRUM", "RUNWAY", "GLIDERPOSITION", "WINCHPOSITION"};
    
    public void SetCard(int index)
    {
        final CardLayout layout = (CardLayout)this.getLayout();
        layout.show(this, tabNames[index]);
    }

    public void clear()
    {
        /*pilotPanel.clear();
        sailplanePanel.clear();
        airfieldPanel.clear();
        runwayPanel.clear();
        gliderPositionPanel.clear();
        winchPositionPanel.clear();*/
    }
    /**
     * Creates new form ParameterSelectionPanel
     */
    public ParameterSelectionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new CardLayout(0, 0));

        //pilotPanel = new PilotPanel();
        //sailplanePanel = new SailplanePanel();
        //airfieldPanel = new AirfieldPanel((CardLayout) getLayout(), this);
        //runwayPanel = new RunwayPanel((CardLayout) getLayout(), this);
        //gliderPositionPanel = new GliderPositionPanel((CardLayout) getLayout(), this);
        //winchPositionPanel = new WinchPositionPanel((CardLayout) getLayout(), this);
        //drumPanel = new DrumPanel();

        //this.add(tabNames[0], pilotPanel);

        //this.add(tabNames[1], sailplanePanel);
        
        /*this.add(tabNames[2], airfieldPanel);
        
        this.add(tabNames[3], drumPanel);

        this.add(tabNames[4], runwayPanel);

        this.add(tabNames[5], gliderPositionPanel);

        this.add(tabNames[6], winchPositionPanel);*/

        
    }// </editor-fold>//GEN-END:initComponents
    
    public void update(String s){};
    
    public void update()
    {
        /*pilotPanel.update();
        sailplanePanel.update();
        airfieldPanel.update("1");
        runwayPanel.update("2");
        gliderPositionPanel.update("3");
        winchPositionPanel.update("4");
        drumPanel.update();*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PilotPanel pilotPanel;
    private SailplanePanel sailplanePanel;
    private AirfieldPanel airfieldPanel;
    private DrumPanel drumPanel;
    private RunwayPanel runwayPanel;
    private GliderPositionPanel gliderPositionPanel;
    private WinchPositionPanel winchPositionPanel;
    // End of variables declaration//GEN-END:variables
}
