/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Configuration;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Matt
 */
public class AirfieldUnitsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AirfieldUnitsPanel
     */
    public AirfieldUnitsPanel() {
        initComponents();
    }

    public int getSelectedIndices(){
        return airfieldLengthSelection.getSelectedIndex();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        airfieldLengthSelection = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Airfield/Runway/Position Entry Units");

        jLabel2.setText("Length:");

        airfieldLengthSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Meters (m)", "Feet (ft)", "Millimeters (mm)", "Centimeters (cm)", "Kilometers (Km)" }));

        jLabel3.setText("includes: Altitude, Max Length");
        try {
            airfieldLengthSelection.setSelectedIndex(DatabaseUtilities.DatabaseUnitSelectionUtilities.getAirfieldDistanceUnit());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AirfieldUnitsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(airfieldLengthSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(airfieldLengthSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox airfieldLengthSelection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
