/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Configuration;

/**
 *
 * @author Matt
 */
public class UnitSelection extends javax.swing.JFrame {
    
    // the following UnitLists store the lists of
    // possible units for each category
    UnitList lengthUnits = new UnitList(5);
    UnitList tensionUnits = new UnitList(3);
    UnitList weightUnits = new UnitList(2);
    UnitList velocityUnits = new UnitList(4);
    UnitList tempUnits = new UnitList(2);
    UnitList pressureUnits = new UnitList(5);
    
    // selectedUnits stores the units selected by the user
    // for each category and their respective conversion factor
    //      0 - length
    //      1 - tension
    //      2 - weight
    //      3 - velocity
    //      4 - temperature
    //      5 - pressure
    UnitList selectedUnits;
    
    /**
     * Creates new form UnitSelection
     */
    public UnitSelection() {
        initComponents();
        lengthUnits.add("cm", 0.01);
        lengthUnits.add("ft", 0.3048);
        lengthUnits.add("km", 1000);
        lengthUnits.add("m", 1);
        lengthUnits.add("mm", 0.001);
        
        tensionUnits.add("kgf", 9.80665);
        tensionUnits.add("N", 1);
        tensionUnits.add("lbs", 4.44822);
        
        weightUnits.add("kg", 9.80665);
        weightUnits.add("lbs", 4.44822);
        
        velocityUnits.add("km/s", 0.277778);
        velocityUnits.add("kn", 0.51444);
        velocityUnits.add("m/s", 1);
        velocityUnits.add("mph", 0.44704);
        
        tempUnits.add("C", 0);
        tempUnits.add("F", 0);
        
        pressureUnits.add("bar", 100000);
        pressureUnits.add("kPa", 1000);
        pressureUnits.add("MPa", 1000000);
        pressureUnits.add("mbar", 100);
        pressureUnits.add("psi", 6894.75729);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lengthComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tensionComboBox = new javax.swing.JComboBox();
        OKButton = new javax.swing.JButton();
        weightComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        velocityComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        tempComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        pressureComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Unit Selection");

        jLabel2.setText("Length:");

        lengthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Feet (ft)", "Centimeters (cm)", "Kilometers (km)", "Meters (m)", "Millimeters (mm)" }));

        jLabel3.setText("Tension:");

        tensionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kilogram-Force (kgf)", "Newtons (N)", "Pound-Force (lbf)" }));

        OKButton.setText("OK");
        OKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKButtonMouseClicked(evt);
            }
        });

        weightComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kilograms (kg)", "Pounds (lbs)" }));

        jLabel4.setText("Weight:");

        jLabel5.setText("Velocity:");

        velocityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kilometers/Hour (km/h)", "Knots (kn)", "Meters/Second (m/s)", "Miles/Hour (mph)" }));

        jLabel6.setText("Temperature:");

        tempComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celsius (C)", "Fahrenheit (F)" }));

        jLabel7.setText("Pressure:");

        pressureComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bar (bar)", "Kilopascals (kPa)", "Megapascals (MPa)", "Millibar (mbar)", "Pounds/Sq. Inch (psi)" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OKButton)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(velocityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(weightComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tensionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lengthComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tempComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pressureComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lengthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tensionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(velocityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tempComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pressureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OKButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKButtonMouseClicked
        selectedUnits = new UnitList(6);
        
        int i = lengthComboBox.getSelectedIndex();
        selectedUnits.add(lengthUnits.labels[i], lengthUnits.conversionFactors[i]);
        
        i = tensionComboBox.getSelectedIndex();
        selectedUnits.add(tensionUnits.labels[i], tensionUnits.conversionFactors[i]);
        
        i = weightComboBox.getSelectedIndex();
        selectedUnits.add(weightUnits.labels[i], weightUnits.conversionFactors[i]);

        i = velocityComboBox.getSelectedIndex();
        selectedUnits.add(velocityUnits.labels[i], velocityUnits.conversionFactors[i]);
        
        i = tempComboBox.getSelectedIndex();
        selectedUnits.add(tempUnits.labels[i], 0);
        
        i = pressureComboBox.getSelectedIndex();
        selectedUnits.add(pressureUnits.labels[i], pressureUnits.conversionFactors[i]);

        System.out.println(selectedUnits);
        this.dispose();
    }//GEN-LAST:event_OKButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnitSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnitSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnitSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnitSelection().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox lengthComboBox;
    private javax.swing.JComboBox pressureComboBox;
    private javax.swing.JComboBox tempComboBox;
    private javax.swing.JComboBox tensionComboBox;
    private javax.swing.JComboBox velocityComboBox;
    private javax.swing.JComboBox weightComboBox;
    // End of variables declaration//GEN-END:variables
}
