/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DatabaseUtilities;

import DataObjects.Pilot;
import ParameterSelection.Capability;
import ParameterSelection.PilotSelectionPanel;
import ParameterSelection.Preference;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Chris
 */
public class PilotModificationPanel extends javax.swing.JPanel {
    private ArrayList<Pilot> names = new ArrayList<Pilot>();
    
    /**
     * Creates new form PilotModificationPanel
     */
    public PilotModificationPanel() {
        initPilotList();
        initComponents();
    }
    
    private void initPilotList() {
        try{
            names = (ArrayList) DatabaseUtilities.DatabaseDataObjectUtilities.getPilots();
            if (names == null)
                names = new ArrayList<>();
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());           
        } catch (ClassNotFoundException ex) {
            // TODO change exception case
            Logger.getLogger(PilotSelectionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pilotJList = new javax.swing.JList();
        pilotNameInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstNameDisplay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lastNameDisplay = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        weightDisplay = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        emergencyContactDisplay = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        emergencyMedInfoDisplay = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        capabilitySlider = new javax.swing.JSlider();
        preferenceSlider = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        DefaultListModel pilotModel = new DefaultListModel();
        for(Object str: names){
            pilotModel.addElement(str);
        }
        pilotJList.setModel(pilotModel);
        pilotJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilotJListMouseClicked(evt);
            }
        });
        pilotJList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pilotJListKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(pilotJList);

        pilotNameInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pilotNameInputKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Search:");

        jLabel3.setText("First Name:");

        firstNameDisplay.setEditable(false);

        jLabel4.setText("Last Name:");

        lastNameDisplay.setEditable(false);

        jLabel5.setText("Capability:");

        jLabel6.setText("Preference:");

        jLabel7.setText("Weight:");

        weightDisplay.setEditable(false);

        emergencyContactDisplay.setEditable(false);
        emergencyContactDisplay.setColumns(20);
        emergencyContactDisplay.setRows(5);
        jScrollPane2.setViewportView(emergencyContactDisplay);

        emergencyMedInfoDisplay.setEditable(false);
        emergencyMedInfoDisplay.setColumns(20);
        emergencyMedInfoDisplay.setRows(5);
        jScrollPane3.setViewportView(emergencyMedInfoDisplay);

        jLabel8.setText("Emergency Contact:");

        jLabel9.setText("Emergency Medical Info:");

        capabilitySlider.setMajorTickSpacing(1);
        capabilitySlider.setMaximum(2);
        capabilitySlider.setPaintTicks(true);
        capabilitySlider.setSnapToTicks(true);

        preferenceSlider.setMajorTickSpacing(1);
        preferenceSlider.setMaximum(2);
        preferenceSlider.setPaintTicks(true);
        preferenceSlider.setSnapToTicks(true);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("Student");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setText("Proficient");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setText("Advanced");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setText("Mild");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setText("Nominal");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setText("Aggressive");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pilotNameInput))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(firstNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(lastNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(weightDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel11))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(capabilitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel14)
                                                .addGap(37, 37, 37)
                                                .addComponent(jLabel15))
                                            .addComponent(preferenceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jScrollPane3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pilotNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weightDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(capabilitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preferenceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pilotJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilotJListMouseClicked
        // TODO add your handling code here:
        Pilot pilot = (Pilot) pilotJList.getSelectedValue();
        pilotSelected(pilot);
    }//GEN-LAST:event_pilotJListMouseClicked

    private void pilotJListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pilotJListKeyReleased
        // TODO add your handling code here:
        Pilot pilot = (Pilot) pilotJList.getSelectedValue();
        pilotSelected(pilot);
    }//GEN-LAST:event_pilotJListKeyReleased

    private void pilotNameInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pilotNameInputKeyReleased
         // TODO add your handling code here:
        String matchstring = pilotNameInput.getText();
        DefaultListModel pilotModel = new DefaultListModel();
        
        // TODO Change from String specific to type Pilot
        for(Pilot plt : names){
            if(plt.getFirstName().toUpperCase().startsWith(matchstring.toUpperCase())) {
                pilotModel.addElement(plt);
            }
            else if(plt.getLastName().toUpperCase().startsWith(matchstring.toUpperCase())) {
                pilotModel.addElement(plt);
            }
        }
        
        pilotJList.setModel(pilotModel);
    }//GEN-LAST:event_pilotNameInputKeyReleased

    private void pilotSelected(Pilot pilot) {
        firstNameDisplay.setText(pilot.getFirstName());
        lastNameDisplay.setText(pilot.getLastName());
        weightDisplay.setText(String.valueOf(pilot.getWeight()));
        weightDisplay.setEditable(true);
        emergencyContactDisplay.setText(pilot.getEmergencyContact());
        emergencyContactDisplay.setEditable(true);
        emergencyMedInfoDisplay.setText(pilot.getMedInfo());
        emergencyMedInfoDisplay.setEditable(true);
        capabilitySlider.setValue(Capability.convertCapabilityStringToNum(pilot.getCapability()));
        preferenceSlider.setValue(Preference.convertPreferenceStringToNum(pilot.getPreference()));
    }
    
    public Pilot getUpdatedPilot() {
        int weight = 0;
        try {
            weight = Integer.parseInt(weightDisplay.getText());
        } catch (NumberFormatException e) {
            weightDisplay.setBackground(new Color(255, 105, 105));
            return null;
        }
        Pilot updatedPilot = new Pilot(lastNameDisplay.getText(),
                firstNameDisplay.getText(),
                weight, 
                Capability.convertCapabilityNumToString(capabilitySlider.getValue()), 
                Preference.convertPreferenceNumToString(preferenceSlider.getValue()), 
                emergencyContactDisplay.getText(), 
                emergencyMedInfoDisplay.getText());
        return updatedPilot;
        
    }
    
    public Pilot getSelectedPilot() {
        if(pilotJList.getSelectedIndex() >= 0) {
            return (Pilot) pilotJList.getSelectedValue();
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider capabilitySlider;
    private javax.swing.JTextArea emergencyContactDisplay;
    private javax.swing.JTextArea emergencyMedInfoDisplay;
    private javax.swing.JTextField firstNameDisplay;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastNameDisplay;
    private javax.swing.JList pilotJList;
    private javax.swing.JTextField pilotNameInput;
    private javax.swing.JSlider preferenceSlider;
    private javax.swing.JTextField weightDisplay;
    // End of variables declaration//GEN-END:variables
}
