/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Wizards;

/**
 *
 * @author Matt
 */
public class PreWizard extends Wizard {

    Wizard selectedWizard;
    
    /**
     * Creates new form PreWizard
     */
    public PreWizard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        windowLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        pilotButton = new javax.swing.JRadioButton();
        gliderButton = new javax.swing.JRadioButton();
        airfieldButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        windowLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        windowLabel.setText("Data Entry Wizard");

        submitButton.setText("Submit");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });

        buttonGroup1.add(pilotButton);
        pilotButton.setText("New Pilot");

        buttonGroup1.add(gliderButton);
        gliderButton.setText("New Glider");

        buttonGroup1.add(airfieldButton);
        airfieldButton.setText("New Airfield");
        airfieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airfieldButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(submitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilotButton)
                            .addComponent(windowLabel)
                            .addComponent(gliderButton)
                            .addComponent(airfieldButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(windowLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pilotButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gliderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airfieldButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        try
        {
            if(pilotButton.isSelected())
            {
                selectedWizard = new Wizard_Pilot();
            }else if(gliderButton.isSelected())
            {
                //selectedWizard = new Wizard_Sailplane();
            }else if(airfieldButton.isSelected())
            {
                //selectedWizard = new Wizard_Airfield();
            }    

            selectedWizard.setVisible(true);
            this.dispose();
        }catch(NullPointerException e){
            //ew = new ErrWindow("Please select pilot, glider, or airfield before submitting.");
        }
    }//GEN-LAST:event_submitButtonMouseClicked

    private void airfieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airfieldButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airfieldButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreWizard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton airfieldButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton gliderButton;
    private javax.swing.JRadioButton pilotButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel windowLabel;
    // End of variables declaration//GEN-END:variables
}
