/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Wizards;

import DataObjects.Pilot;
import ParameterSelection.Capability;
import ParameterSelection.Preference;
import java.sql.SQLException;

/**
 *
 * @author Matt
 */
public class Wizard_Pilot extends Wizard {
    
    /**
     * Creates new form Wizard_Pilot
     */
    public Wizard_Pilot() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pilotRequiredPanel2 = new PilotRequiredPanel();
        pilotOptionalPanel2 = new PilotOptionalPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        windowLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        windowLabel.setText("Pilot Data Entry Wizard");

        submitButton.setText("Submit");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                submitButtonMousePressed(evt);
            }
        });

        jTabbedPane1.addTab("Required Info", pilotRequiredPanel2);
        jTabbedPane1.addTab("Optional Info", pilotOptionalPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(windowLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(submitButton)))
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(windowLabel)
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMousePressed
        if(pilotRequiredPanel2.isComplete())
        {
            submitData();
            this.dispose();
        }
            
    }//GEN-LAST:event_submitButtonMousePressed

    protected void submitData(){
        String[] names = pilotRequiredPanel2.getPilotName().split(" ");
        String firstName;
        String lastName;
        if (names.length >= 2) {
            firstName = names[0];
            lastName = names[1]; 
        }
        else {
            firstName = names[0];
            lastName = names[1]; 
        }
        int weight = pilotRequiredPanel2.getWeight();
        String capability = Capability.convertCapabilityNumToString(pilotRequiredPanel2.getCapability());
        System.out.println(pilotRequiredPanel2.getCapability());
        String preference = Preference.convertPreferenceNumToString(pilotRequiredPanel2.getPreference());
        System.out.println(pilotRequiredPanel2.getPreference());
        
        Pilot newPilot = new Pilot(firstName, lastName, weight, capability, preference, "", "");
        try{
            DatabaseUtilities.DatabaseUtilities.addPilotToDB(newPilot);
        }catch(SQLException e1) {
            //TODO Report error
        }catch (ClassNotFoundException e2) {
            //TODO Report error
        }
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wizard_Pilot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wizard_Pilot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wizard_Pilot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wizard_Pilot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wizard_Pilot().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private PilotOptionalPanel pilotOptionalPanel2;
    private PilotRequiredPanel pilotRequiredPanel2;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel windowLabel;
    // End of variables declaration//GEN-END:variables
}
