//DEAD CLASS FOR REFERENCE

package AddEditPanels;

import DataObjects.Airfield;
import Configuration.UnitLabelUtilities;
import DatabaseUtilities.DatabaseUnitSelectionUtilities;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Matt
 */
public class AirfieldWizardPanel extends javax.swing.JPanel {
    
    /*
    
    ArrayList<Airfield> airfields = new ArrayList();
    
    /**
     * Creates new form AirfieldWizardPanel
     *
    public AirfieldWizardPanel() {
        initComponents();
    }
    
    public void populate(){
        DefaultListModel airfieldListModel = new DefaultListModel();
        for(Airfield a: airfields){
            airfieldListModel.addElement(a.getName());
        }
        airfieldMenu.setModel(airfieldListModel);
    }
    
    public String getName(){
        return nameField.getText();
    }
    
    public String getDesignator(){
        return designatorField.getText();
    }
    
    public String getAirfieldLocation(){
        return locationField.getText();
    }
    
    public int getAltitude(){
        return Integer.parseInt(altitudeField.getText());
    }
    
    public int getMagneticVariation(){
        return Integer.parseInt(magVarField.getText());
    }

    public boolean isComplete(Airfield a)
    {
        a.setName(nameField.getText());
        if(a.getName().isEmpty()){
            return false;
        }
        a.setDesignator(designatorField.getText());
        if(a.getDesignator().isEmpty()){
            return false;
        }
        a.setLocation(locationField.getText());
        if(a.getLocation().isEmpty()){
            return false;
        }
        a.setAltitude(Integer.parseInt(altitudeField.getText()));
        if(altitudeField.getText().isEmpty()){
            return false;
        }
        a.setMagneticVariation(Integer.parseInt(magVarField.getText()));
        if(magVarField.getText().isEmpty()){
            return false;
        }
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        jScrollPane1 = new javax.swing.JScrollPane();
        airfieldMenu = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        designatorField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        altitudeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        altitudeUnits = new javax.swing.JLabel();
        // locationUnits = new javax.swing.JLabel();
        magVarField = new javax.swing.JTextField();
        DatabaseUnitSelectionUtilities units = new DatabaseUnitSelectionUtilities();
        UnitLabelUtilities unitsLabel = new UnitLabelUtilities();
        airfieldMenu.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        airfieldMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                airfieldMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(airfieldMenu);
        
        jLabel1.setText("Name:");
        
        jLabel2.setText("Designator:");
        
        jLabel3.setText("Location:");
        
        jLabel4.setText("Existing Airfields:");
        
        jLabel5.setText("Manual Entry:");
        
        jLabel6.setText("Altitude:");
        
        jLabel7.setText("Magnetic Variation:");
        try {
            altitudeUnits.setText(unitsLabel.lenghtUnitInexToString(DatabaseUnitSelectionUtilities.getAirfieldDistanceUnit()));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AirfieldWizardPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                  .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                              .addComponent(jLabel3)
                                                                                              .addComponent(jLabel2)
                                                                                              .addComponent(jLabel6)
                                                                                              .addComponent(jLabel7)
                                                                                              .addComponent(jLabel1)
                                                                                              .addComponent(jLabel5))
                                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                              
                                                                                              .addGroup(layout.createSequentialGroup()
                                                                                                        .addComponent(altitudeField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(altitudeUnits))
                                                                                              .addGroup(layout.createSequentialGroup()
                                                                                                        .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                              // .addComponent(locationUnits)
                                                                                              .addGroup(layout.createSequentialGroup()
                                                                                                        .addComponent(magVarField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                              .addGroup(layout.createSequentialGroup()
                                                                                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                              .addGroup(layout.createSequentialGroup()
                                                                                                        .addComponent(designatorField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                              
                                                                                              ))))
                                                      .addComponent(jLabel4))
                                            
                                            .addContainerGap())
                                  );
        layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5))
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                              .addGap(4, 4, 4)
                                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel1))
                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(designatorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel3)
                                                                        //.addComponent(locationUnits)
                                                                        .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(altitudeUnits)
                                                                        .addComponent(altitudeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(magVarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                );
    }    
    private void airfieldMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airfieldMenuMouseClicked
        Airfield selected = airfields.get(airfieldMenu.getSelectedIndex());
        
        altitudeField.setText("" + selected.getAltitude());
        designatorField.setText(selected.getDesignator());
        locationField.setText(selected.getLocation());
        magVarField.setText("" + selected.getMagneticVariation());
        nameField.setText(selected.getName());
         
    }//GEN-LAST:event_airfieldMenuMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList airfieldMenu;
    private javax.swing.JTextField altitudeField;
    private javax.swing.JTextField designatorField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel altitudeUnits;
    //private javax.swing.JLabel locationUnits;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationField;
    private javax.swing.JTextField magVarField;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
    
    */
}
